email:
  provider:
    user:
    password:
    host: SSL0.OVH.NET
    ssl: true
  to:
  cc:
port: 3001
host: localhost
client:
  # Cover image - Image on the background, the first visible thing when loading the website.
  covers: # Automatic - One image within the folder will be chosen randomly.
    items: []

  # Gallery of office pictures.
  galleryOffice:
    items:
      - filename: "office1.jpg"
        legend: "La Chatounerie, vue de l'extérieur"
      - filename: "office2.jpg"
        legend: "Notre arbre à chats, tant convoité"
      - filename: "office3.jpg"
        legend: "Chatounerie vue de l'intérieur (droite porte d'entrée)"
      - filename: "office4.jpg"
        legend: "Chatounerie vue de l'intérieur (gauche porte d'entrée"

  # Gallery of cats pictures.
  galleryCats:
    items: []

  # Google Map config. (API key)
  googleMap:
    key:
